// Isolated headless browser: no user desktop input or live credentials.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {billingFixture} from './billing-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve('dist'),artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const file=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))throw Error('scope');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:750,height:680},deviceScaleFactor:1,colorScheme:'dark'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(data=>{window.__fixture=data;window.__commands=[];window.__CQG_TEST_BRIDGE__={snapshot:async()=>structuredClone(window.__fixture),command:async(action,payload)=>{window.__commands.push({action,payload});if(action==='chart_history')return{ok:true,data:structuredClone(window.__fixture.view.analytics)};return {ok:true,data:{}};},window_action:async()=>({ok:true})};},billingFixture());
  await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);
  await page.locator('.app-shell.ready').waitFor();await page.evaluate(()=>window.__CQG_TEST__.pausePolling());await page.waitForTimeout(400);
  assert.equal(await page.getByTestId('pool-remaining').innerText(),'62.0%');
  assert.equal(await page.locator('.pool-track').getAttribute('aria-valuemax'),'100');
  assert.deepEqual(await page.locator('.pool-track i').evaluateAll(nodes=>nodes.map(n=>n.style.width)),['23.5%','38.5%']);
  assert.equal(await page.locator('.refresh-progress-row').count(),2);
  assert.equal(await page.locator('.device-row .avatar img').count(),3);
  assert.ok((await page.locator('.device-row .avatar img').evaluateAll(images=>images.map(i=>i.complete&&i.naturalWidth>0))).every(Boolean));
  assert.equal(await page.locator('.device-usage').first().innerText(),'112.50%');
  assert.equal(await page.getByTestId('connection-state').nth(1).innerText(),'在线');
  for(const size of [{width:750,height:680},{width:730,height:650}]){
    await page.setViewportSize(size);await page.waitForTimeout(200);
    const box=await page.getByTestId('device-row').last().boundingBox();assert.ok(box.y+box.height<=size.height);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  }
  await page.setViewportSize({width:750,height:680});await page.waitForTimeout(200);
  await page.screenshot({path:path.join(artifacts,'billing-overview-dark.png')});
  await page.getByRole('button',{name:'筛选账号',exact:true}).click();await page.getByRole('option',{name:'账号2',exact:true}).click();
  const filtered=await page.evaluate(()=>window.__CQG_TEST__.getState());
  assert.equal(filtered.pie.quotaTotals.person1,undefined);assert.equal(filtered.pie.quotaTotals.person3,3);
  await page.getByRole('button',{name:'筛选账号',exact:true}).click();await page.getByRole('option',{name:'两账号合计',exact:true}).click();
  await page.getByTestId('device-row').first().click();await page.locator('.user-pool-summary').waitFor();
  assert.equal(await page.locator('.user-account-breakdown article').count(),2);
  await page.screenshot({path:path.join(artifacts,'billing-member.png')});
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.getByTestId('nav-stats').click();await page.locator('.pool-journal').waitFor();
  assert.equal(await page.getByTestId('cycle-record').count(),2);
  await page.locator('.pool-stats-head').getByRole('button',{name:'账号2',exact:true}).click();assert.equal(await page.getByTestId('cycle-record').count(),1);
  await page.screenshot({path:path.join(artifacts,'billing-stats.png')});
  await page.getByTestId('cycle-reset-tag').click();
  await page.getByRole('button',{name:'确认原因',exact:true}).click();
  assert.ok((await page.evaluate(()=>window.__commands)).some(c=>c.action==='group_rule'&&c.payload.kind==='reset'&&c.payload.cause==='official'));
  await page.getByTestId('nav-accounts').click();
  await page.locator('.account-item').first().waitFor();
  assert.deepEqual(await page.locator('.account-item strong').allTextContents(),['账号1','账号2']);
  await page.getByTestId('nav-sync').click();
  await page.locator('.paired-device').first().waitFor();
  assert.equal(await page.locator('.paired-device').count(),2);
  assert.ok((await page.getByTestId('join-progress').innerText()).includes('已连接共享组'));
  await page.locator('.paired-device').first().getByRole('button',{name:'移除',exact:true}).click();
  await page.locator('.modal').getByRole('button',{name:'确认',exact:true}).click();
  assert.ok((await page.evaluate(()=>window.__commands)).some(c=>c.action==='device_remove'&&c.payload.device==='fixture-peer'));
  await page.getByTestId('nav-settings').click();await page.locator('.group-policy-panel').waitFor();
  const toggle=page.getByRole('switch',{name:'跨周期补偿',exact:true});assert.equal(await toggle.isEnabled(),true);
  await toggle.click();assert.ok((await page.evaluate(()=>window.__commands)).some(c=>c.action==='compensation_toggle'&&c.payload.revision===1&&c.payload.enabled===true));
  await page.screenshot({path:path.join(artifacts,'billing-settings.png')});
  await page.evaluate(()=>{window.__fixture.view.shared_group.can_manage=false;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});
  assert.equal(await toggle.isDisabled(),true);
  await page.getByTestId('nav-overview').click();await page.getByTestId('pool-remaining').waitFor();
  await page.evaluate(()=>{window.__fixture.settings.theme='light';window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});await page.waitForTimeout(300);
  await page.screenshot({path:path.join(artifacts,'billing-overview-light.png')});
  assert.deepEqual(errors,[]);console.log('BILLING_UI_PERCENT_AVATARS_FILTERS_RULES_LAYOUT_OK');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
