// Isolated headless browser: no live credentials or user desktop input.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {billingFixture} from './billing-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve('dist'),artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{if(req.url==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))throw Error('scope');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:750,height:680},deviceScaleFactor:1,colorScheme:'dark'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.addInitScript(data=>{window.__fixture=data;window.__commands=[];window.__CQG_TEST_BRIDGE__={snapshot:async()=>structuredClone(window.__fixture),command:async(action,payload)=>{window.__commands.push({action,payload});if(action==='network_retry')Object.assign(window.__fixture.network_guard,{checking:true,state:'checking'});if(action==='chart_history')return{ok:true,data:structuredClone(window.__fixture.view.analytics)};return{ok:true,data:{}};},window_action:async()=>({ok:true})};},billingFixture());
  await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);
  await page.locator('.app-shell.ready').waitFor();await page.evaluate(()=>window.__CQG_TEST__.pausePolling());
  const status=page.getByTestId('network-status'),dialog=page.getByRole('dialog');
  const guard=(state,ip='203.0.113.20',extra={})=>({baseline:'203.0.113.20',state,current_ip:ip,observations:['chatgpt.com','api.openai.com'].map(host=>({host,ip,error:null})),checked_at:Date.now()/1000,checking:false,error:null,...extra});
  const apply=async data=>{await page.evaluate(data=>{window.__fixture.network_guard=data;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));},data);await page.waitForTimeout(250);};
  const dismiss=async()=>{await dialog.getByRole('button',{name:'关闭对话框',exact:true}).click();await page.waitForTimeout(250);};
  assert.match(await status.innerText(),/未设置/);assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),false);
  await status.click();assert.match(await page.getByTestId('network-title').innerText(),/住宅IP对齐/);
  assert.equal(await dialog.getByRole('button',{name:'设置为住宅IP基准',exact:true}).isDisabled(),true);
  await apply(guard('unconfigured','203.0.113.20',{baseline:null}));
  await dialog.getByRole('button',{name:'设置为住宅IP基准',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.find(c=>c.action==='network_baseline')),{action:'network_baseline',payload:{revision:1}});
  await apply(guard('aligned'));assert.equal(await dialog.count(),1);assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),true);
  await apply(guard('aligned'));assert.equal(await dialog.count(),1);await dismiss();
  await status.click();await dialog.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();
  assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dialog.getByRole('button',{name:'确认',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.filter(c=>c.action==='network_baseline').at(-1)),{action:'network_baseline',payload:{revision:1,confirmed:true}});
  const mismatch=guard('mismatch','198.51.100.9');await apply(mismatch);
  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');
  assert.equal(await page.getByTestId('network-baseline').innerText(),'203.0.113.20');assert.equal(await page.getByTestId('network-current').innerText(),'198.51.100.9');
  assert.equal(await page.locator('.app-shell.network-warning').count(),1);
  await page.screenshot({path:path.join(artifacts,'ip-alignment-mismatch.png')});
  await dismiss();await apply({...mismatch,checked_at:Date.now()/1000});assert.equal(await dialog.count(),0);
  await page.getByRole('button',{name:'设置',exact:true}).click();assert.equal(await page.locator('.app-shell.network-warning').count(),1);
  await page.getByRole('button',{name:'概览',exact:true}).click();await status.click();await dialog.getByRole('button',{name:'重试',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.filter(c=>c.action==='network_retry').at(-1)),{action:'network_retry',payload:{}});
  assert.equal(await page.locator('.app-shell.network-warning').count(),1);assert.equal(await dialog.getByRole('button',{name:'检测中…',exact:true}).isDisabled(),true);
  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),false);
  await apply(guard('error',null,{error:'出口检测超时',observations:[{host:'chatgpt.com',ip:null,error:'连接超时'},{host:'api.openai.com',ip:null,error:'连接超时'}]}));
  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP检测失败');assert.match(await dialog.innerText(),/出口检测超时/);
  assert.equal(await page.locator('.app-shell.network-warning').count(),1);await apply(guard('aligned'));
  assert.equal(await page.locator('.app-shell.network-warning').count(),0);assert.equal(await dialog.count(),0);
  // A different dialog remains open; the pending warning appears after dismissal.
  await status.click();await dialog.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();await apply(mismatch);
  assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dialog.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByTestId('network-title').waitFor();assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');
  await apply(guard('aligned'));await status.click();await dialog.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();
  await apply(guard('aligned'));assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dismiss();
  await apply(guard('unconfigured','203.0.113.20',{baseline:null,checked_at:Date.now()/1000-90}));await status.click();
  assert.equal(await dialog.getByRole('button',{name:'设置为住宅IP基准',exact:true}).isDisabled(),true);
  await apply(guard('mismatch',null,{observations:[{host:'chatgpt.com',ip:'203.0.113.20',error:null},{host:'api.openai.com',ip:'198.51.100.9',error:null}]}));
  assert.equal(await dialog.getByRole('button',{name:'更新住宅IP基准',exact:true}).isDisabled(),true);
  await apply(guard('aligned'));await page.evaluate(()=>{window.__fixture.view.shared_group.can_manage=false;window.__fixture.view.account_summaries[1].paused=true;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});
  await status.click();assert.equal(await dialog.getByRole('button',{name:'更新住宅IP基准',exact:true}).count(),0);await dismiss();
  assert.equal(await page.getByTestId('pool-refresh-card').locator('.account-reset-row').nth(1).locator('strong').innerText(),'已停用');
  assert.equal(await page.getByTestId('pool-refresh-card').locator('.account-reset-row').nth(1).locator('small').count(),0);
  const layout=await status.evaluate(el=>{const card=el.closest('.sync-card'),last=card.lastElementChild,a=card.getBoundingClientRect(),b=last.getBoundingClientRect();return{height:a.height,overflow:b.bottom>a.bottom-5};});
  assert.equal(layout.height,126);assert.equal(layout.overflow,false);
  await page.screenshot({path:path.join(artifacts,'ip-alignment-overview.png')});assert.deepEqual(errors,[]);
  console.log('IP alignment UI: states, baseline permissions, retry, persistent border, modal ownership, failure deduplication, and paused countdown passed');
}finally{await browser.close();server.close();}
