// Isolated headless browser: no live credentials or user desktop input.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {billingFixture} from './billing-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve('dist'),artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{if(req.url==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))throw Error('scope');res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.jpg')?'image/jpeg':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:750,height:680},deviceScaleFactor:1,colorScheme:'dark'}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  const fixture=billingFixture(),reportAt=Date.now()/1000-30;
  const peerReport={ip:'198.51.100.24',country:'日本',location:'日本 东京',purity:'纯净',risk_score:12,checked_at:reportAt,error:null,risk_error:null,risk_at:reportAt};
  fixture.view.network_members=[{id:'person1',name:'橙猫猫',online:true,device:'fixture-local',report:{...peerReport,ip:'192.0.2.1',purity:null,risk_score:null},history:[]},{id:'person2',name:'A',online:false,device:'fixture-peer',report:peerReport,history:[{...peerReport,previous_ip:'192.0.2.24',device:'fixture-peer',device_name:'A的电脑'},{...peerReport,previous_ip:'192.0.2.23',ip:'192.0.2.24',checked_at:reportAt-3600,purity:'极度纯净',risk_score:0,device:'fixture-peer',device_name:'A的电脑'}]},{id:'person3',name:'第三人',online:false,device:'fixture-third',report:null,history:[]}];
  await page.addInitScript(data=>{window.__fixture=data;window.__commands=[];window.__CQG_TEST_BRIDGE__={snapshot:async()=>structuredClone(window.__fixture),command:async(action,payload)=>{window.__commands.push({action,payload});if(action==='network_retry')Object.assign(window.__fixture.network_guard,{checking:true,state:'checking'});if(action==='chart_history'||action==='member_history')return{ok:true,data:structuredClone(window.__fixture.view.analytics)};return{ok:true,data:{}};},window_action:async()=>({ok:true})};},fixture);
  await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);
  await page.locator('.app-shell.ready').waitFor();await page.evaluate(()=>window.__CQG_TEST__.pausePolling());
  const status=page.getByTestId('network-status'),dialog=page.getByRole('dialog'),settings=page.getByTestId('network-settings'),local=page.locator('[data-testid=network-member][data-member=person1]'),peer=page.locator('[data-testid=network-member][data-member=person2]'),third=page.locator('[data-testid=network-member][data-member=person3]');
  const guard=(state,ip='203.0.113.20',extra={})=>({baseline:'203.0.113.20',state,current_ip:ip,observations:[{host:'ping0.cc',ip,error:null,country:'美国',location:'弗吉尼亚州'}],country:'美国',location:'弗吉尼亚州',purity:'极度纯净',risk_score:2,risk_error:null,risk_at:Date.now()/1000,check_interval:10,risk_cache_seconds:600,checked_at:Date.now()/1000,checking:false,codex_running:true,error:null,...extra});
  const apply=async data=>{await page.evaluate(data=>{window.__fixture.network_guard=data;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));},data);await page.waitForTimeout(250);};
  const dismiss=async()=>{await dialog.getByRole('button',{name:'关闭对话框',exact:true}).click();await page.waitForTimeout(250);};
  const navigate=async name=>{await page.getByRole('button',{name,exact:true}).click();await page.waitForTimeout(250);};
  assert.match(await status.innerText(),/未设置/);assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),false);
  await status.click();assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP对齐');
  assert.equal(await dialog.getByRole('button',{name:/住宅IP基准/}).count(),0);
  assert.equal(await local.getByTestId('member-risk').innerText(),'Ping0 风控值 未获取');await dismiss();
  await navigate('设置');await settings.waitFor();await settings.scrollIntoViewIfNeeded();
  assert.equal(await settings.getByRole('button',{name:'设置为住宅IP基准',exact:true}).isDisabled(),true);
  assert.equal(await page.locator('section.page article').last().evaluate(el=>el.classList.contains('maintenance-panel')),true);
  await apply(guard('unconfigured','203.0.113.20',{baseline:null}));
  await settings.getByRole('button',{name:'设置为住宅IP基准',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.find(c=>c.action==='network_baseline')),{action:'network_baseline',payload:{revision:1}});
  await apply(guard('aligned'));await settings.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();
  assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dialog.getByRole('button',{name:'确认',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.filter(c=>c.action==='network_baseline').at(-1)),{action:'network_baseline',payload:{revision:1,confirmed:true}});
  await settings.scrollIntoViewIfNeeded();await page.waitForTimeout(250);await page.screenshot({path:path.join(artifacts,'ip-alignment-settings-0611.png')});
  await navigate('概览');await status.click();await apply(guard('aligned'));assert.equal(await dialog.count(),1);
  assert.equal(await dialog.getByRole('button',{name:/住宅IP基准/}).count(),0);
  assert.equal(await dialog.getByTestId('network-member').count(),3);
  const cards=await dialog.getByTestId('network-member').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width};}));
  assert.ok(cards.every(card=>Math.abs(card.y-cards[0].y)<1));assert.ok(cards[0].x<cards[1].x&&cards[1].x<cards[2].x);assert.ok(cards.every(card=>card.width<200));
  assert.equal(await local.getByTestId('member-purity').evaluate(el=>getComputedStyle(el).color),'rgb(115, 215, 176)');

  const ipStyle=await local.getByTestId('member-ip').evaluate(el=>({background:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color,parentColor:getComputedStyle(el.parentElement).color,border:getComputedStyle(el).borderColor,dot:getComputedStyle(el,'::before').backgroundColor,dotContent:getComputedStyle(el,'::before').content}));
  assert.equal(ipStyle.background,'rgba(0, 0, 0, 0)');assert.equal(ipStyle.color,ipStyle.parentColor);assert.equal(ipStyle.border,'rgb(115, 215, 176)');assert.equal(ipStyle.dot,'rgb(115, 215, 176)');assert.equal(ipStyle.dotContent,'""');
  assert.equal(await local.getByTestId('member-ip').innerText(),'203.0.113.20');assert.equal(await peer.getByTestId('member-ip').innerText(),'198.51.100.24');
  assert.equal(await peer.locator('.network-member-presence').innerText(),'离线');assert.equal(await third.getByTestId('member-ip').innerText(),'未上报');
  await peer.locator('.network-history summary').click();assert.equal(await peer.getByTestId('network-history-row').count(),2);assert.equal(await peer.locator('.network-history-purity').first().evaluate(el=>getComputedStyle(el).color),'rgb(115, 215, 176)');assert.match(await peer.locator('.network-history').innerText(),/192.0.2.24/);assert.match(await peer.getByTestId('network-ip-change').first().innerText(),/192.0.2.24 →\s*198.51.100.24/);assert.doesNotMatch(await peer.locator('.network-history').innerText(),/日本 · 日本/);
  await third.locator('.network-history summary').click();assert.equal(await third.getByTestId('network-history-row').count(),0);assert.match(await third.locator('.network-history').innerText(),/暂无历史记录/);
  await page.screenshot({path:path.join(artifacts,'ip-alignment-history-0611.png')});
  await peer.locator('.network-history summary').click();await third.locator('.network-history summary').click();
  assert.equal(await local.getByTestId('member-location').innerText(),'美国 · 弗吉尼亚州');
  await apply(guard('aligned','203.0.113.20',{location:'美国 加利福尼亚州 洛杉矶'}));assert.equal(await local.getByTestId('member-location').innerText(),'美国 加利福尼亚州 洛杉矶');
  assert.equal(await page.evaluate(()=>window.__fixture.network_guard.location),'美国 加利福尼亚州 洛杉矶');
  assert.match(await local.locator('.network-history summary').innerText(),/0 条/);

  assert.equal(await local.getByTestId('member-purity').innerText(),'极度纯净');assert.equal(await local.getByTestId('member-risk').innerText(),'Ping0 风控值 2%');
  assert.match(await dialog.innerText(),/每10秒检测/);assert.match(await dialog.innerText(),/并非 OpenAI 评定/);assert.doesNotMatch(await dialog.innerText(),/98%|双域名/);
  await apply(guard('aligned','203.0.113.20',{risk_score:0}));assert.equal(await local.getByTestId('member-risk').innerText(),'Ping0 风控值 0%');
  await apply(guard('aligned','203.0.113.20',{risk_score:null,purity:null,risk_error:'查询超时'}));
  assert.equal(await local.getByTestId('member-risk').innerText(),'Ping0 风控值 未获取');assert.equal(await local.getByTestId('member-purity').innerText(),'未获取');
  assert.match(await dialog.innerText(),/纯度数据暂不可用：查询超时/);assert.equal(await page.locator('.app-shell.network-warning').count(),0);
  assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),true);
  await apply(guard('aligned'));await page.screenshot({path:path.join(artifacts,'ip-alignment-ping0-0611.png')});await dismiss();
  const arrowGap=await status.evaluate(el=>el.querySelector('.network-status-arrow').getBoundingClientRect().left-el.querySelector('.network-status-label').getBoundingClientRect().right);
  assert.ok(arrowGap>=0&&arrowGap<=7,`arrow gap ${arrowGap}`);
  const mismatch=guard('mismatch','198.51.100.9');
  await apply({...mismatch,codex_running:false});assert.equal(await dialog.count(),0);assert.equal(await page.locator('.app-shell.network-warning').count(),1);
  await page.evaluate(()=>window.dispatchEvent(new Event('network-alert')));await page.waitForTimeout(250);assert.equal(await dialog.count(),0);
  await status.click();assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');await dismiss();
  await apply(mismatch);

  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');
  assert.equal(await page.getByTestId('network-baseline').innerText(),'203.0.113.20');assert.equal(await page.getByTestId('network-current').innerText(),'198.51.100.9');
  assert.equal(await page.locator('.app-shell.network-warning').count(),1);await page.screenshot({path:path.join(artifacts,'ip-alignment-mismatch-0611.png')});
  await dismiss();await apply({...mismatch,checked_at:Date.now()/1000,risk_score:3,observations:[{...mismatch.observations[0],location:'更新地区'}]});assert.equal(await dialog.count(),0);
  await navigate('设置');assert.equal(await page.locator('.app-shell.network-warning').count(),1);
  // Native-host event forces this alert back to overview, even after normal-poll dismissal.
  const freshMismatch=guard('mismatch','198.51.100.8');
  await page.evaluate(data=>{window.__fixture.network_guard=data;Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'hidden'});window.dispatchEvent(new Event('network-alert'));},freshMismatch);
  await page.getByTestId('network-title').waitFor();assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().page),'overview');
  assert.equal(await page.getByTestId('network-current').innerText(),'198.51.100.8');await dismiss();await navigate('设置');
  await page.evaluate(()=>window.dispatchEvent(new Event('network-alert')));await page.getByTestId('network-title').waitFor();
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().page),'overview');
  await dialog.getByRole('button',{name:'重试',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__commands.filter(c=>c.action==='network_retry').at(-1)),{action:'network_retry',payload:{}});
  assert.equal(await page.locator('.app-shell.network-warning').count(),1);assert.equal(await dialog.getByRole('button',{name:'检测中…',exact:true}).isDisabled(),true);
  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');assert.equal(await status.evaluate(el=>el.classList.contains('aligned')),false);
  await apply(guard('error',null,{error:'出口检测超时',observations:[{host:'ping0.cc',ip:null,error:'连接超时'}],country:null,location:null,purity:null,risk_score:null}));
  assert.equal(await page.locator('.app-shell.network-warning').count(),0);assert.equal(await dialog.count(),0);
  await page.evaluate(()=>window.dispatchEvent(new Event('network-alert')));await page.waitForTimeout(250);assert.equal(await dialog.count(),0);
  await apply(guard('error',null,{error:'出口检测超时',observations:[{host:'ping0.cc',ip:null,error:'连接超时'}],country:null,location:null,purity:null,risk_score:null}));assert.equal(await dialog.count(),0);
  await status.click();
  assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP检测失败');assert.match(await dialog.innerText(),/出口检测超时/);
  assert.equal(await local.getByTestId('member-location').innerText(),'地区未获取');
  assert.equal(await page.locator('.app-shell.network-warning').count(),0);await dismiss();await apply(guard('aligned'));
  assert.equal(await page.locator('.app-shell.network-warning').count(),0);assert.equal(await dialog.count(),0);
  // Normal polls do not replace another active dialog; recovery only closes the warning.
  await navigate('设置');await settings.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();await apply(mismatch);
  assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dialog.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByTestId('network-title').waitFor();assert.equal(await page.getByTestId('network-title').innerText(),'住宅IP没有对齐');
  await apply(guard('aligned'));await settings.getByRole('button',{name:'更新住宅IP基准',exact:true}).click();
  await apply(guard('aligned'));assert.equal(await dialog.locator('h2').innerText(),'更新住宅IP基准');await dismiss();
  await page.evaluate(()=>window.dispatchEvent(new Event('network-alert')));await page.waitForTimeout(250);
  assert.equal(await dialog.count(),0);assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().page),'settings');
  await apply(guard('unconfigured','203.0.113.20',{baseline:null,checked_at:Date.now()/1000-90}));
  assert.equal(await settings.getByRole('button',{name:'设置为住宅IP基准',exact:true}).isDisabled(),true);
  await apply(guard('unconfigured','203.0.113.20',{baseline:null,observations:[{host:'ping0.cc',ip:null,error:'连接超时'}]}));
  assert.equal(await settings.getByRole('button',{name:'设置为住宅IP基准',exact:true}).isDisabled(),true);
  await apply(guard('aligned'));await page.evaluate(()=>{window.__fixture.view.shared_group.can_manage=false;window.__fixture.view.account_summaries[1].paused=true;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});
  assert.equal(await settings.getByRole('button',{name:/住宅IP基准/}).count(),0);
  await navigate('概览');await status.click();assert.equal(await dialog.getByRole('button',{name:/住宅IP基准/}).count(),0);await dismiss();
  assert.equal(await page.getByTestId('pool-refresh-card').locator('.account-reset-row').nth(1).locator('strong').innerText(),'已停用');
  assert.equal(await page.getByTestId('pool-refresh-card').locator('.account-reset-row').nth(1).locator('small').count(),0);
  const layout=await status.evaluate(el=>{const card=el.closest('.sync-card'),last=card.lastElementChild,a=card.getBoundingClientRect(),b=last.getBoundingClientRect();return{height:a.height,overflow:b.bottom>a.bottom-5};});
  assert.equal(layout.height,126);assert.equal(layout.overflow,false);
  await page.screenshot({path:path.join(artifacts,'ip-alignment-overview-0611.png')});
  await page.getByTestId('device-row').nth(1).click();const personal=page.getByTestId('personal-ip-details');await personal.waitFor();await personal.scrollIntoViewIfNeeded();
  const personalLayout=await dialog.evaluate(el=>{const total=el.querySelector('.user-cycle-primary').getBoundingClientRect(),ip=el.querySelector('.personal-ip-details').getBoundingClientRect(),models=el.querySelector('.user-model-list').getBoundingClientRect();return{total:{x:total.x,y:total.y,bottom:total.bottom},ip:{x:ip.x,y:ip.y,bottom:ip.bottom,height:ip.height},modelsTop:models.top};});
  assert.ok(Math.abs(personalLayout.total.y-personalLayout.ip.y)<1);assert.ok(personalLayout.ip.x>personalLayout.total.x);assert.equal(personalLayout.ip.height,210);assert.ok(personalLayout.modelsTop>personalLayout.ip.bottom);
  assert.equal(await dialog.getByTestId('personal-ip-details').count(),1);assert.match(await dialog.locator('.user-cycle-primary').innerText(),/总用量/);assert.match(await dialog.locator('.user-cycle-primary').innerText(),/额度消耗/);
  assert.equal(await personal.getByTestId('member-ip').innerText(),'198.51.100.24');assert.equal(await personal.getByTestId('member-purity').innerText(),'纯净');
  assert.equal(await dialog.getByTestId('shared-consumption-card').count(),1);
  await personal.locator('.network-history summary').click();assert.equal(await personal.getByTestId('network-history-row').count(),2);await personal.scrollIntoViewIfNeeded();assert.equal(await personal.evaluate(el=>el.getBoundingClientRect().height),210);assert.ok(await personal.locator('.network-history-list').evaluate(el=>el.scrollHeight>el.clientHeight&&el.clientHeight<=125));
  await page.screenshot({path:path.join(artifacts,'ip-alignment-personal-0611.png')});await dismiss();
  await page.evaluate(()=>{window.__fixture.settings.theme='light';window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});await apply(mismatch);
  assert.equal(await dialog.locator('.network-error').first().evaluate(el=>getComputedStyle(el).color),'rgb(199, 47, 72)');
  assert.equal(await local.getByTestId('member-purity').evaluate(el=>getComputedStyle(el).color),'rgb(24, 124, 88)');
  await page.screenshot({path:path.join(artifacts,'ip-alignment-light-0611.png')});
  assert.deepEqual(errors,[]);
  console.log('Ping0 alignment UI: settings controls, compact arrow, country/location, purity and risk 0/unknown, Codex-gated native alert, three members and history, personal IP details, warning lifecycle, and paused countdown passed');
}finally{await browser.close();server.close();}
