// Headless, private browser context only. Never attaches to the user's browser.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fixture} from './fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve('dist'),artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname;const file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:750,height:545},deviceScaleFactor:1,colorScheme:'dark'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const initial=fixture();initial.settings.force_relay=true;
  initial.view.analytics.models.push('codex-auto-review','gpt-5.9','gpt-5.10');
  await page.addInitScript(data=>{window.__commands=[];window.__fixture=data;window.__CQG_TEST_BRIDGE__={snapshot:async()=>structuredClone(window.__fixture),command:async(action,payload)=>{
    window.__commands.push({action,payload});const settings=window.__fixture.settings;
    if(action==='settings_save'&&payload.settings.theme)settings.theme=payload.settings.theme;
    if(action==='device_order_save')(settings.device_order??={})[payload.account]=payload.devices;
    if(action==='note_save')((settings.device_notes??={})[payload.account]??={})[payload.device]=payload.text;
    if(action==='color_save')((settings.device_colors??={})[payload.account]??={})[payload.device]=payload.color;
    return {ok:true,data:{}};
  },window_action:async action=>{window.__commands.push({host:action});return action==='browse_program'?{ok:true,data:['C:/isolated-test/extra-codex.exe']}:{ok:true};}};},initial);
  await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);
  await page.locator('.app-shell.ready').waitFor();await page.waitForTimeout(550);
  assert.deepEqual(errors,[]);
  assert.equal(await page.getByTestId('device-row').count(),2);
  const rows=await page.getByTestId('device-row').first().boundingBox();assert.ok(rows.y>300);
  assert.equal(await page.getByTestId('device-row').first().evaluate(n=>getComputedStyle(n).borderTopWidth),'0px');
  const summaryBox=await page.locator('.summary-grid').boundingBox();
  assert.ok(rows.x<summaryBox.x&&rows.width>summaryBox.width,'device cards extend beyond the summary grid');
  const last=await page.getByTestId('device-row').last().boundingBox();assert.ok(last.y+last.height<=555,'both device rows fully visible');
  assert.equal(await page.locator('.donut-svg text').count(),0);
  assert.ok(!(await page.getByTestId('pie-chart').innerText()).includes('%'));
  assert.ok((await page.getByTestId('pie-chart').innerText()).includes('81.27M'));
  assert.ok((await page.getByTestId('pie-chart').innerText()).includes('148.36M'));
  const pieCard=await page.getByTestId('pie-chart').boundingBox(),pieSelector=await page.locator('.pie-period').boundingBox(),pieTitle=await page.locator('.donut-card h2').boundingBox();
  assert.ok(pieSelector.y-pieCard.y<=8&&pieCard.x+pieCard.width-pieSelector.x-pieSelector.width>=9,'pie period sits at the top right');
  assert.ok(Math.abs(pieSelector.y+pieSelector.height/2-pieTitle.y-pieTitle.height/2)<=2,'pie period aligns with the title');
  assert.equal(await page.locator('.overview').evaluate(e=>e.scrollHeight<=e.clientHeight),true);
  assert.equal(await page.locator('.donut-tooltip').innerText(),'81.27M Token','local Token is visible without hover');
  const tokenBox=await page.locator('.donut-tooltip').boundingBox();
  assert.ok(pieCard.x+pieCard.width-tokenBox.x-tokenBox.width<=14,'default Token sits at the bottom right');
  await page.locator('.legend-row').last().dispatchEvent('pointerenter');
  assert.equal(await page.locator('.donut-tooltip').innerText(),'148.36M Token');
  await page.locator('.legend-row').last().dispatchEvent('pointerleave');
  assert.equal(await page.locator('.donut-tooltip').innerText(),'81.27M Token','pointer leave restores local usage');
  const arcLengths=await page.locator('.donut-piece circle').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('stroke-dasharray').split(' ')[0])));
  assert.ok(Math.abs(arcLengths.reduce((a,b)=>a+b,0)-(314.159-6))<.01,'two devices retain visible gaps without changing Token totals');
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.summary.epoch.used=80;window.__CQG_TEST__.applySnapshot(data);});
  await page.waitForTimeout(450);
  const track=await page.locator('.quota-progress').boundingBox(),fill=await page.locator('.quota-progress i').boundingBox();
  assert.ok(Math.abs(fill.x+fill.width-track.x-track.width)<1,'remaining quota is anchored at the right edge');
  assert.ok(Math.abs(fill.width/track.width-.2)<.01,'20 percent remaining retains 20 percent width');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  const normalUsageColor=await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color);
  for(const [used,color] of [[91,'rgb(237, 141, 152)'],[90,'rgb(232, 191, 117)'],[80,normalUsageColor],[null,normalUsageColor]]){
    await page.evaluate(used=>{const data=structuredClone(window.__fixture);data.view.summary.epoch.used=used;window.__CQG_TEST__.applySnapshot(data);},used);
    assert.equal(await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color),color);
    assert.equal(await page.getByTestId('official-remaining').innerText(),used===null?'—':(100-used)+'%');
    assert.equal(await page.locator('.quota-progress').getAttribute('aria-valuenow'),used===null?null:String(100-used));
    if(used===91||used===90)assert.equal(await page.locator('.quota-progress i').evaluate(node=>getComputedStyle(node).backgroundColor),color);
  }
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.summary.epoch=null;window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('official-remaining').innerText(),'—');
  assert.equal(await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color),normalUsageColor);
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.evaluate(()=>{
    window.__nativeDateNow=Date.now;window.__clockStart=Date.now();
    Date.now=()=>window.__clockStart;
    const data=structuredClone(window.__fixture);data.view.summary.epoch.reset_at=window.__clockStart/1000+7200;
    window.__countdownData=data;window.__CQG_TEST__.applySnapshot(data);
  });
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'2.0 小时');
  const dateBox=await page.getByTestId('refresh-date').boundingBox(),refreshBox=await page.locator('.refresh-card').boundingBox();
  assert.ok(dateBox.x-refreshBox.x>=13&&dateBox.x-refreshBox.x<=15&&refreshBox.y+refreshBox.height-dateBox.y-dateBox.height>=8,'refresh date sits at bottom left with padding');
  await page.evaluate(()=>{Date.now=()=>window.__clockStart+3600e3;window.__CQG_TEST__.applySnapshot(structuredClone(window.__countdownData));});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'1.0 小时');
  await page.evaluate(()=>{Date.now=()=>window.__clockStart+7200e3;window.__CQG_TEST__.applySnapshot(structuredClone(window.__countdownData));});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'等待刷新');
  await page.evaluate(()=>{const data=structuredClone(window.__countdownData);delete data.view.summary.epoch.reset_at;window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'—');
  await page.evaluate(()=>{Date.now=window.__nativeDateNow;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','在线']);
  const usagePill=await page.locator('.device-state.using').boundingBox();
  assert.ok(usagePill.width<110&&usagePill.height===27,'usage badge is compact and keeps its original centered height');
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);data.view.peers={};
    data.view.summary.devices.find(d=>d.id==='fixture-local').online=false;
    data.view.summary.devices.find(d=>d.id==='fixture-peer').online=true;
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','离线'],'connection badges do not use monitoring heartbeats');
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);
    data.view.summary.devices.find(d=>d.id==='fixture-peer').online=false;
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','在线'],'connected peer stays online when its monitoring heartbeat is stale');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  const badges=await page.getByTestId('connection-state').evaluateAll(nodes=>nodes.map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,font:getComputedStyle(n).fontSize})));
  assert.deepEqual(badges,[{width:58,height:28,font:'12px'},{width:58,height:28,font:'12px'}]);
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.peers={};window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('connection-state').last().evaluate(n=>getComputedStyle(n).color),'rgb(237, 141, 152)');
  await page.screenshot({path:path.join(artifacts,'offline-badge.png')});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();
  await page.getByRole('option',{name:'一小时',exact:true}).click();
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.chart-bar').count(),30,'hour view contains thirty 2-minute buckets');
  assert.ok((await page.locator('.trend-card h2').innerText()).includes('最近 1 小时'));
  assert.equal((await page.locator('.charts-grid').boundingBox()).height,200);
  await page.screenshot({path:path.join(artifacts,'hour-preview.png')});
  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();
  await page.getByRole('option',{name:'一天',exact:true}).click();
  await page.getByRole('button',{name:'曲线',exact:true}).click();await page.waitForTimeout(400);
  await page.screenshot({path:path.join(artifacts,'overview.png')});
  const mutations=await page.evaluate(async()=>{
    let count=0;const observer=new MutationObserver(list=>count+=list.length);
    document.querySelectorAll('.trend-svg,.donut-svg').forEach(node=>observer.observe(node,{subtree:true,attributes:true,childList:true}));
    for(let i=0;i<20;i++)window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));
    await new Promise(r=>setTimeout(r,400));observer.disconnect();return count;
  });
  assert.equal(mutations,0,'identical polling performs zero SVG mutation or animation');
  await page.getByTestId('device-row').first().click();
  assert.equal(await page.getByRole('heading',{name:'用户设置',exact:true}).count(),1);
  assert.equal(await page.locator('.palette button').count(),8);
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.waitForTimeout(200);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).selectedDevice,'','closing user settings clears selection');
  assert.equal(await page.locator('.device-heading').count(),0);
  await page.getByRole('button',{name:'筛选模型',exact:true}).click();
  assert.deepEqual(await page.locator('.select-option>span:first-child').allTextContents(),['全部模型','gpt-5.10','gpt-5.9','gpt-5.5','gpt-5.3-codex']);
  await page.locator('.select-menu').evaluate(e=>e.dataset.identity='persistent-menu');
  for(let i=0;i<20;i++)await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.locator('.select-menu').getAttribute('data-identity'),'persistent-menu');
  assert.equal(await page.getByTestId('device-row').first().evaluate(e=>e.classList.contains('selected')),false);
  await page.screenshot({path:path.join(artifacts,'dropdown.png')});
  await page.getByRole('option',{name:'gpt-5.5',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().model),'gpt-5.5');
  await page.getByRole('button',{name:'筛选用户',exact:true}).click();
  await page.getByRole('option',{name:'橙猫猫 · 本机',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().user),'fixture-local');
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(350);
  assert.equal(await page.locator('.chart-bar').count(),24);
  await page.screenshot({path:path.join(artifacts,'bars.png')});
  await page.getByTestId('device-row').first().click();
  assert.equal(await page.locator('.palette button').count(),8);
  await page.locator('.user-note-label input').fill('测试工作站');
  await page.locator('.palette button').nth(4).click();
  await page.getByRole('button',{name:'保存用户设置',exact:true}).click();
  await page.locator('.modal-backdrop').waitFor({state:'hidden'});
  assert.equal(await page.locator('.device-row.selected').count(),0,'saving user settings clears the device highlight');
  assert.equal(await page.evaluate(()=>window.__commands.at(-1).action),'color_save');
  assert.ok((await page.getByTestId('device-row').first().innerText()).includes('测试工作站'));
  const firstRow=await page.getByTestId('device-row').first().boundingBox(),secondRow=await page.getByTestId('device-row').last().boundingBox();
  await page.mouse.move(firstRow.x+80,firstRow.y+25);await page.mouse.down();
  await page.mouse.move(secondRow.x+80,secondRow.y+30,{steps:10});await page.mouse.up();await page.waitForTimeout(220);
  assert.equal(await page.locator('.modal-backdrop').count(),0,'dragging does not open user settings');
  assert.deepEqual(await page.getByTestId('device-row').evaluateAll(rows=>rows.map(row=>row.dataset.deviceId)),['fixture-peer','fixture-local']);
  assert.equal(await page.locator('.legend-name').first().innerText(),'DESKTOP-N41609F');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.getByTestId('device-row').first().getAttribute('data-device-id'),'fixture-peer');
  for(const target of ['accounts','sync','settings','help','overview']){await page.getByTestId('nav-'+target).click();await page.waitForTimeout(340);await page.screenshot({path:path.join(artifacts,target+'.png')});}
  await page.getByTestId('nav-sync').click();await page.waitForTimeout(330);
  await page.getByRole('button',{name:'高级连接设置',exact:true}).click();
  const relay=page.getByRole('checkbox',{name:'仅使用加密中转',exact:true});
  assert.equal(await relay.isChecked(),true,'existing relay preference initializes the connection form');
  await relay.uncheck();
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await relay.isChecked(),false,'polling preserves an edited connection preference');
  await page.getByRole('button',{name:'保存连接设置',exact:true}).click();
  const connection=await page.evaluate(()=>window.__commands.filter(c=>c.action==='connection_save').at(-1));
  assert.deepEqual(connection.payload,{force_relay:false});
  await page.getByTestId('nav-settings').click();await page.waitForTimeout(330);
  await page.getByTestId('settings-user').last().click();
  assert.equal(await page.locator('.modal h2').innerText(),'用户设置');
  assert.equal(await page.locator('.user-note-label input').inputValue(),'测试工作站');
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.waitForTimeout(200);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).selectedDevice,'','closing user settings clears selection');
  await page.getByRole('button',{name:'添加 EXE',exact:true}).click();
  assert.ok((await page.locator('.program-list').innerText()).includes('extra-codex.exe'));
  await page.getByRole('button',{name:'保存监测设置',exact:true}).click();
  const saved=await page.evaluate(()=>window.__commands.filter(c=>c.action==='settings_save').at(-1));
  assert.deepEqual(Object.keys(saved.payload.settings).sort(),['autostart','codex_home','interval','multiplier','name','program_paths','quota']);
  await page.getByRole('switch',{name:'Codex 自动限额'}).click();
  await page.getByRole('button',{name:'确认',exact:true}).click();
  const limit=await page.evaluate(()=>window.__commands.filter(c=>c.action==='limit_toggle').at(-1));
  assert.equal(limit.payload.account,'fixture-account');assert.equal(limit.payload.confirmed,true);
  await page.getByTestId('nav-overview').click();await page.waitForTimeout(330);
  await page.getByRole('button',{name:'曲线',exact:true}).click();
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);
    for(const row of data.view.analytics.windows.day.rows)if(row.device==='fixture-local'&&row.model==='gpt-5.5')row.tokens=row.bucket===12?9e6:1000;
    window.__fixture=data;window.__CQG_TEST__.applySnapshot(data);
  });await page.waitForTimeout(400);
  async function hoverAt(fraction){await page.evaluate(fraction=>{const hit=document.querySelector('[data-testid="trend-hit"]'),r=hit.getBoundingClientRect();hit.dispatchEvent(new PointerEvent('pointermove',{clientX:r.left+r.width*fraction,clientY:r.top+30,bubbles:true}));},fraction);await page.waitForTimeout(170);return page.locator('.chart-tooltip').boundingBox();}
  const lowA=await hoverAt(.08),lowB=await hoverAt(.18),peakTip=await hoverAt(12/23);
  assert.ok(Math.abs(lowA.y-lowB.y)<.5,'tooltip keeps a fixed baseline away from the curve');
  assert.ok(peakTip.y<lowA.y-10,'tooltip rises to avoid a high peak');
  const hitBox=await page.getByTestId('trend-hit').boundingBox();
  assert.ok(peakTip.y+peakTip.height<hitBox.y+hitBox.height*.1-5,'tooltip clears the actual peak');
  await page.screenshot({path:path.join(artifacts,'tooltip-peak-avoidance.png')});
  assert.deepEqual(errors,[]);
  const measure=await page.evaluate(async()=>{
    const frames=[];let previous=performance.now(),at=previous;
    await new Promise(resolve=>{function tick(now){frames.push(now-previous);previous=now;if(now-at<1000){const target=document.querySelector('[data-testid="trend-hit"]'),bounds=target.getBoundingClientRect();target.dispatchEvent(new PointerEvent('pointermove',{clientX:bounds.x+bounds.width*(.5+Math.sin(now/180)*.4),clientY:bounds.y+40,bubbles:true}));requestAnimationFrame(tick);}else resolve();}requestAnimationFrame(tick);});
    frames.sort((a,b)=>a-b);return {frames:frames.length,median:frames[Math.floor(frames.length*.5)],p95:frames[Math.floor(frames.length*.95)]};
  });
  assert.equal(await page.locator('.chart-hover').count(),1);
  await page.reload();
  await page.locator('.app-shell.ready').waitFor();await page.waitForTimeout(600);
  assert.equal(await page.locator('.toast').count(),0);
  assert.equal(await page.getByRole('button',{name:'筛选模型',exact:true}).innerText(),'全部模型');
  await page.screenshot({path:path.join(artifacts,'overview.png')});
  assert.equal(await page.getByRole('button',{name:'界面主题',exact:true}).innerText(),'');
  assert.equal(await page.locator('.theme-icon').count(),1);
  async function chooseTheme(label){await page.getByRole('button',{name:'界面主题',exact:true}).click();await page.getByRole('option',{name:label,exact:true}).click();await page.waitForTimeout(250);}
  await chooseTheme('白天模式');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  assert.equal(await page.locator('.app-shell').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(243, 245, 248)');
  assert.ok(await page.locator('.titlebar').evaluate(n=>n.scrollWidth<=n.clientWidth));
  await page.screenshot({path:path.join(artifacts,'theme-light.png')});
  await page.getByTestId('device-row').first().click();await page.waitForTimeout(200);
  await page.screenshot({path:path.join(artifacts,'theme-light-modal.png')});
  await page.keyboard.press('Escape');
  await page.emulateMedia({colorScheme:'dark'});
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await chooseTheme('跟随系统');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.emulateMedia({colorScheme:'light'});await page.waitForTimeout(100);
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await chooseTheme('黑夜模式');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:path.join(artifacts,'theme-dark.png')});
  assert.deepEqual(errors,[]);
  await writeFile(path.join(artifacts,'result.json'),JSON.stringify({ok:true,errors,headlessFrameSample:measure},null,2));
  console.log('OFFLINE_VUE_UI_DATA_LAYOUT_SELECTION_MENU_ALL_PAGES_OK',JSON.stringify(measure));
}finally{await browser.close();await new Promise(r=>server.close(r));}
