// Headless, private browser context only. Never attaches to the user's browser.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fixture} from './fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve('dist'),artifacts=path.resolve('test-artifacts');await mkdir(artifacts,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname;const file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}const data=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:750,height:545},deviceScaleFactor:1,colorScheme:'dark'});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const initial=fixture();initial.settings.force_relay=true;


  initial.view.analytics.models.push('codex-auto-review','gpt-5.9','gpt-5.10');
  await page.addInitScript(data=>{window.__commands=[];window.__fixture=data;window.__CQG_TEST_BRIDGE__={snapshot:async()=>structuredClone(window.__fixture),command:async(action,payload)=>{
    window.__commands.push({action,payload});const settings=window.__fixture.settings;
    if(action==='chart_history'){window.__historyActive=(window.__historyActive||0)+1;window.__historyPeak=Math.max(window.__historyPeak||0,window.__historyActive);if(window.__historyDelay)await new Promise(r=>setTimeout(r,window.__historyDelay));const data=structuredClone(window.__fixture.view.analytics);for(const key of (payload.period==='day'?['day']:['hour','hour_curve'])){const w=data.windows[key],count=w.count,multiple=payload.period==='day'?32:26;w.count*=multiple;w.start=Math.floor(Math.min(data.at,payload.end)/w.step)*w.step-(w.count-1)*w.step;for(const name of ['rows','quota_rows','quota_pending_rows','quota_estimate_rows'])w[name]=Array.from({length:multiple},(_,i)=>i).flatMap(part=>(w[name]||[]).map(row=>({...row,bucket:row.bucket+part*count})));}window.__historyActive--;return {ok:true,data};}
    if(action==='compensation_toggle')window.__fixture.view.summary.compensation_enabled=payload.enabled;if(action==='settings_save')for(const key of ['theme','quota_display'])if(key in payload.settings)settings[key]=payload.settings[key];
    if(action==='device_order_save')(settings.device_order??={})[payload.account]=payload.devices;
    if(action==='note_save')((settings.device_notes??={})[payload.account]??={})[payload.device]=payload.text;
    if(action==='color_save')((settings.device_colors??={})[payload.account]??={})[payload.device]=payload.color;
    return {ok:true,data:{}};
  },window_action:async action=>{window.__commands.push({host:action});return action==='browse_program'?{ok:true,data:['C:/isolated-test/extra-codex.exe']}:{ok:true};}};},initial);
  await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);
  await page.locator('.app-shell.ready').waitFor();await page.evaluate(()=>window.__CQG_TEST__.pausePolling());await page.waitForTimeout(550);
  assert.deepEqual(errors,[]);
  assert.equal(await page.getByRole('button',{name:'趋势时间范围',exact:true}).innerText(),'每小时');
  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();await page.getByRole('option',{name:'每天',exact:true}).click();await page.waitForTimeout(450);
  const daySlider=page.getByRole('slider',{name:'最近30天时间滑块'}),liveDay=(await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start;
  assert.equal(await daySlider.evaluate(n=>Number(n.max)-Number(n.min)),30*86400);
  assert.equal(await daySlider.getAttribute('step'),'3600','day slider selects whole-hour positions');
  assert.equal(await daySlider.evaluate(n=>Number(n.min)%3600),0);
  assert.equal(await daySlider.evaluate(n=>Number(n.max)%3600),0);
  const dragFrames=await daySlider.evaluate(async n=>{
    const start=performance.now(),end=Number(n.max),frames=[];
    await new Promise(resolve=>{function tick(at){const elapsed=at-start;if(elapsed<240){n.value=end-(Math.floor(elapsed/16)+1)*3600;n.dispatchEvent(new Event('input',{bubbles:true}));}frames.push({elapsed,end:window.__CQG_TEST__.getState().chartEnd});if(elapsed<750)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});return frames;
  });
  assert.ok(new Set(dragFrames.filter(f=>f.elapsed<240).map(f=>f.end)).size>=6,'continuous hourly dragging keeps rendering while new targets arrive');
  assert.ok(dragFrames.filter(f=>f.end!==null).every((f,i,all)=>!i||f.end<=all[i-1].end),'dragging backwards never kicks the curve forwards');
  await daySlider.evaluate(n=>{n.value=n.max;n.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(650);
  await daySlider.evaluate(n=>{n.value=Number(n.max)-3*86400;n.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(600);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start,liveDay-3*86400);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.points.length,24);
  await daySlider.evaluate(n=>{n.value=n.min;n.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(600);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start,liveDay-30*86400);
  await page.getByRole('button',{name:'筛选模型',exact:true}).click();await page.getByRole('option',{name:'gpt-5.10',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await daySlider.isDisabled(),true,'a model with no history cannot scroll into empty dates');
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).chartEnd,null);
  await page.getByRole('button',{name:'筛选模型',exact:true}).click();await page.getByRole('option',{name:'全部模型',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await daySlider.isDisabled(),false);

  assert.equal(await page.locator('.device-state').first().innerText(),'Codex 使用中');

  assert.equal(await page.locator('.device-runtime-model').count(),0,'current model display is removed');
  assert.equal(await page.locator('.device-usage').first().evaluate(n=>getComputedStyle(n).fontSize),'16px');
  const runtimeLayout=await page.getByTestId('device-row').first().evaluate(n=>{const label=n.querySelector('.device-label').getBoundingClientRect(),badge=n.querySelector('.connection-badge').getBoundingClientRect(),runtime=n.querySelector('.device-state').getBoundingClientRect(),tokens=n.querySelector('.device-tokens').getBoundingClientRect();return {nameGap:badge.left-label.right,overlap:badge.right>runtime.left||runtime.right>tokens.left};});
  assert.ok(runtimeLayout.nameGap<=12&&!runtimeLayout.overlap,'online sits close to the name and usage status has its own aligned column');
  const badgePositions=await page.getByTestId('connection-state').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().x));
  assert.ok(Math.abs(badgePositions[0]-badgePositions[1])<.5,'connection badges have a fixed column independent of username length');
  assert.equal(await page.locator('.window-buttons button').count(),3);
  const titleControls=await page.locator('.version,.window-buttons button').evaluateAll(nodes=>nodes.map(n=>({x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,h:n.getBoundingClientRect().height})));
  assert.ok(titleControls.every((n,i)=>!i||n.x>titleControls[i-1].x));
  assert.ok(titleControls.slice(1).every(n=>n.y===titleControls[1].y&&n.h===titleControls[1].h));

  assert.equal(await page.getByTestId('device-row').count(),2);
  await page.evaluate(()=>{window.__originalActivityNow=Date.now;window.__activityNow=Date.now();Date.now=()=>window.__activityNow;window.__activityFixture=structuredClone(window.__fixture);window.__CQG_TEST__.applySnapshot(structuredClone(window.__activityFixture));});
  assert.equal(await page.locator('.device-state.using').count(),1);
  await page.evaluate(()=>{window.__activityNow+=5000;window.__activityFixture.view.summary.devices[0].active=0;window.__CQG_TEST__.applySnapshot(structuredClone(window.__activityFixture));});
  assert.equal(await page.locator('.device-state.using').count(),1,'short sampling gap does not flash idle');
  await page.evaluate(()=>{window.__activityNow+=11000;window.__CQG_TEST__.applySnapshot(structuredClone(window.__activityFixture));});
  assert.equal(await page.locator('.device-state.using').count(),0,'continuous idle expires after fifteen seconds');
  await page.evaluate(()=>{window.__activityFixture.view.summary.devices[1].active=1;window.__CQG_TEST__.applySnapshot(structuredClone(window.__activityFixture));});
  assert.equal(await page.locator('.device-state.using').count(),1);
  await page.evaluate(()=>{window.__activityFixture.view.peers={};window.__CQG_TEST__.applySnapshot(structuredClone(window.__activityFixture));});
  assert.equal(await page.locator('.device-state.using').count(),0,'offline clears activity immediately');
  await page.evaluate(()=>{Date.now=window.__originalActivityNow;const cleared=structuredClone(window.__fixture);cleared.view.identity.account='other-account';window.__CQG_TEST__.applySnapshot(cleared);window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});

  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).user,'','first open defaults to all users');
  assert.equal(await page.getByRole('button',{name:'趋势时间范围',exact:true}).innerText(),'每天');
  assert.equal(await page.locator('.trend-line').count(),2);
  await page.getByRole('button',{name:'筛选用户',exact:true}).click();
  await page.getByRole('option',{name:/^橙猫猫 · 本机/}).click();

  assert.equal(await page.locator('.trend-legend-share').innerText(),(initial.view.analytics.windows.day.rows.filter(r=>r.device==='fixture-local').reduce((sum,r)=>sum+r.tokens,0)/450e6*100).toFixed(1)+'%');
  assert.equal(await page.locator('.trend-legend-share').first().evaluate(n=>getComputedStyle(n).color),'rgb(102, 156, 255)');

  assert.equal(await page.getByTestId('daily-quota-average').innerText(),'26.5% / 天');
  const officialNumber=await page.getByTestId('official-remaining').boundingBox(),dailyNumber=await page.getByTestId('daily-quota-average').boundingBox();
  assert.ok(officialNumber.x+officialNumber.width<=dailyNumber.x,'daily average does not overlap remaining quota');
  const quotaTrack=await page.locator('.quota-progress').boundingBox();
  assert.ok(dailyNumber.y+dailyNumber.height<quotaTrack.y,'daily average sits above the progress bar');
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).user,'fixture-local','explicit local selection is retained');
  assert.ok((await page.getByTestId('cycle-budget').innerText()).includes('450.00M'));
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);Object.assign(data.view.analytics.cycles[0],{source:'联合样本',sample_devices:2,sample_ready:1,sample_segments:0,total_tokens:null});window.__CQG_TEST__.applySnapshot(data);});
  assert.match(await page.getByTestId('cycle-budget').innerText(),/样本 1\/2/);
  assert.match(await page.getByTestId('cycle-budget').innerText(),/等待样本同步/);
  assert.equal(await page.getByTestId('cycle-budget').evaluate(n=>n.scrollWidth<=n.clientWidth),true);
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);Object.assign(data.view.analytics.cycles[0],{source:'联合样本',sample_devices:2,sample_ready:2,sample_segments:5});window.__CQG_TEST__.applySnapshot(data);});
  assert.match(await page.getByTestId('cycle-budget').getAttribute('title'),/2\/2 台已确认，5 段样本/);
  await page.screenshot({path:path.join(artifacts,'joint-budget-samples.png')});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.locator('.donut-tooltip').count(),0);
  assert.deepEqual(await page.locator('.donut-main-share').allTextContents(),['18.1%','33.0%']);
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);for(const w of Object.values(data.view.analytics.windows))w.quota_ready=false;window.__CQG_TEST__.applySnapshot(data);});
  assert.deepEqual(await page.locator('.donut-main-share').allTextContents(),['—','—']);
  assert.equal(await page.locator('.trend-legend-share').innerText(),'—');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  const ordinarySnapshot=await page.evaluate(()=>structuredClone(window.__fixture));
  await page.evaluate(()=>{
    window.__fixture.settings.quota_display='personal';
    const rows=window.__fixture.view.summary.devices;
    rows[0].estimated=0;rows[0].carry=15;rows[0].fair_base_cap=50;
    rows[1].estimated=0;rows[1].carry=-15;rows[1].fair_base_cap=50;
    window.__fixture.view.analytics.windows.cycle.quota_rows=[];
    window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));
  });
  assert.deepEqual(await page.locator('.device-usage').allTextContents(),['0.00%','0.00%']);
  await page.getByTestId('nav-settings').click();await page.waitForTimeout(250);
  const compensation=page.getByRole('switch',{name:'跨周期补偿',exact:true});
  assert.equal(await compensation.getAttribute('aria-checked'),'false');
  await compensation.click();assert.equal(await compensation.getAttribute('aria-checked'),'true');
  await page.getByRole('button',{name:'额度显示基准',exact:true}).click();
  await page.getByRole('option',{name:'补偿显示模式',exact:true}).click();
  await page.getByTestId('nav-overview').click();await page.waitForTimeout(250);
  assert.deepEqual(await page.locator('.device-usage').allTextContents(),['30.00%','-30.00%']);
  await page.screenshot({path:path.join(artifacts,'compensation-display.png')});
  await page.getByTestId('nav-settings').click();await page.waitForTimeout(250);
  await compensation.click();assert.equal(await compensation.getAttribute('aria-checked'),'false');
  await page.getByTestId('nav-overview').click();await page.waitForTimeout(250);
  assert.deepEqual(await page.locator('.device-usage').allTextContents(),['0.00%','0.00%']);
  await page.getByTestId('nav-settings').click();await page.waitForTimeout(250);
  await page.getByRole('button',{name:'额度显示基准',exact:true}).click();
  await page.getByRole('option',{name:'个人额度 = 100%',exact:true}).click();
  await page.getByTestId('nav-overview').click();await page.waitForTimeout(250);
  assert.deepEqual(await page.locator('.device-usage').allTextContents(),['0.00%','0.00%']);
  await page.evaluate(data=>{window.__fixture=data;window.__CQG_TEST__.applySnapshot(data);},ordinarySnapshot);
  await page.getByTestId('nav-stats').click();await page.waitForTimeout(400);
  assert.equal(await page.getByTestId('cycle-record').count(),2);
  assert.equal(await page.getByTestId('cycle-change').first().innerText(),'-10.0%');
  assert.equal(await page.getByTestId('cycle-change').first().evaluate(n=>getComputedStyle(n).color),'rgb(237, 141, 152)');
  assert.equal(await page.getByTestId('cycle-change').first().evaluate(n=>getComputedStyle(n).fontSize),'20px');
  assert.equal(await page.getByTestId('cycle-change').last().innerText(),'—');
  assert.equal(await page.locator('.cycle-change-tokens').first().innerText(),'（50.00M Token）');
  const cycleGeometry=await page.getByTestId('cycle-record').first().evaluate(n=>({tag:n.querySelector('.cycle-reset-tag').getBoundingClientRect().right,head:n.querySelector('.cycle-heading').getBoundingClientRect().right,date:n.querySelector('.cycle-date').getBoundingClientRect().top,track:n.querySelector('.cycle-progress').getBoundingClientRect().bottom}));
  assert.ok(Math.abs(cycleGeometry.tag-cycleGeometry.head)<1);
  assert.ok(cycleGeometry.date>cycleGeometry.track);
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.analytics.cycles[0].reset_type='自然重置';data.view.analytics.cycles[0].change_percent=10;data.view.analytics.cycles[0].change_tokens=50e6;window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('cycle-change').first().innerText(),'+10.0%');
  assert.equal(await page.getByTestId('cycle-reset-tag').first().evaluate(n=>getComputedStyle(n).fontSize),'13px');
  assert.equal(await page.getByTestId('cycle-reset-tag').first().locator('i').count(),0);
  await page.screenshot({path:path.join(artifacts,'cycle-natural-final.png')});
  assert.equal(await page.locator('.cycle-change-tokens.increased').first().innerText(),'（50.00M Token）');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));


  const modelNumberStyle=await page.locator('.cycle-model-card strong').first().evaluate(n=>({font:getComputedStyle(n).fontFamily,line:getComputedStyle(n).lineHeight,shadow:getComputedStyle(n).textShadow,transform:getComputedStyle(n).transform}));
  assert.ok(modelNumberStyle.font.startsWith('"Segoe UI"'));
  assert.equal(modelNumberStyle.line,'20px');
  assert.equal(modelNumberStyle.shadow,'none');
  assert.equal(modelNumberStyle.transform,'none');

  assert.equal(await page.locator('.cycle-progress').first().getAttribute('aria-valuenow'),'53');
  assert.equal(await page.getByTestId('cycle-record').first().locator('.cycle-model-track').count(),4);
  assert.equal(await page.locator('.cycle-model-track').first().evaluate(n=>getComputedStyle(n).height),'4px');
  assert.equal(await page.locator('.cycle-progress').first().evaluate(n=>getComputedStyle(n).height),'8px');
  assert.ok(Math.abs((await page.getByTestId('cycle-record').first().locator('.cycle-model-share b').allTextContents()).reduce((n,text)=>n+parseFloat(text),0)-100)<.2);
  assert.ok(Math.abs(await page.locator('.cycle-progress i').first().evaluate(n=>new DOMMatrix(getComputedStyle(n).transform).a)-.53)<.001);
  assert.ok((await page.getByTestId('cycle-record').first().innerText()).includes('-10.0%'));
  await page.screenshot({path:path.join(artifacts,'cycle-statistics.png')});
  assert.ok((await page.getByTestId('cycle-reference').first().innerText()).includes('等待已结束周期'));
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);
    Object.assign(data.view.analytics.cycles[0],{reference_count:3,reference_total_tokens:500e6,reference_starts:[1,2,3],reduction_tokens:50e6,reduction_percent:10});
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.ok((await page.getByTestId('cycle-reference').first().innerText()).includes('500.00M'));
  assert.equal(await page.getByTestId('cycle-reset-tag').first().innerText(),'原因未确认');
  assert.ok((await page.getByTestId('cycle-reference').first().innerText()).includes('预计减少 ≈ 50.00M Token · 10.0%'));
  await page.screenshot({path:path.join(artifacts,'cycle-reference-average.png')});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));

  await page.getByTestId('nav-overview').click();await page.waitForTimeout(350);
  const rows=await page.getByTestId('device-row').first().boundingBox();assert.ok(rows.y>300);
  assert.equal(await page.getByTestId('device-row').first().evaluate(n=>getComputedStyle(n).borderTopWidth),'0px');
  const summaryBox=await page.locator('.summary-grid').boundingBox();
  assert.ok(rows.x<summaryBox.x&&rows.width>summaryBox.width,'device cards extend beyond the summary grid');
  const last=await page.getByTestId('device-row').last().boundingBox();assert.ok(last.y+last.height<=555,'both device rows fully visible');
  assert.equal(await page.locator('.donut-svg text').count(),0);
  for(const [label,key] of [['每小时','pie_hour'],['每6小时','pie_six_hours'],['每天','today']]){
    await page.getByRole('button',{name:'设备占比时间范围',exact:true}).click();
    await page.getByRole('option',{name:label,exact:true}).click();
    const expected=await page.evaluate(key=>window.__fixture.view.analytics.windows[key].rows.filter(r=>r.device!=='removed-peer').reduce((sum,r)=>sum+r.tokens,0),key);
    assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).pie.total,expected);
  }
  await page.getByRole('button',{name:'设备占比时间范围',exact:true}).click();
  await page.getByRole('option',{name:'本周期',exact:true}).click();
  assert.deepEqual(await page.locator('.donut-main-share').allTextContents(),['18.1%','33.0%']);
  const pieShares=await page.locator('.donut-share').evaluateAll(nodes=>nodes.map(n=>({x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,h:n.getBoundingClientRect().height,weight:getComputedStyle(n).fontWeight})));
  assert.ok(Math.abs(pieShares[0].x-pieShares[1].x)<.5,'pie percentages share one aligned column');
  assert.ok(pieShares.every(n=>Number(n.weight)>=700));
  for(let i=0;i<2;i++){
    const row=await page.locator('.legend-row').nth(i).boundingBox();
    assert.ok(Math.abs(pieShares[i].y+pieShares[i].h/2-row.y-row.height/2)<1,'pie share centers beside both text lines');
  }

  assert.ok((await page.getByTestId('pie-chart').innerText()).includes('81.27M'));
  assert.ok((await page.getByTestId('pie-chart').innerText()).includes('148.36M'));
  const pieCard=await page.getByTestId('pie-chart').boundingBox(),pieSelector=await page.locator('.pie-period').boundingBox(),pieTitle=await page.locator('.donut-card h2').boundingBox();
  assert.ok(pieSelector.y-pieCard.y<=8&&pieCard.x+pieCard.width-pieSelector.x-pieSelector.width>=9,'pie period sits at the top right');
  assert.ok(Math.abs(pieSelector.y+pieSelector.height/2-pieTitle.y-pieTitle.height/2)<=2,'pie period aligns with the title');
  assert.equal(await page.locator('.overview').evaluate(e=>e.scrollHeight<=e.clientHeight),true);
  const tokenBox=await page.getByTestId('cycle-budget').boundingBox();
  assert.ok(pieCard.x+pieCard.width-tokenBox.x-tokenBox.width<=14,'cycle estimate replaces personal total at bottom right');
  assert.equal(await page.locator('.cycle-budget strong').evaluate(n=>getComputedStyle(n).color),'rgb(102, 156, 255)');
  await page.locator('.legend-row').last().dispatchEvent('pointerenter');
  assert.ok((await page.getByTestId('cycle-budget').innerText()).includes('450.00M'));
  await page.locator('.legend-row').last().dispatchEvent('pointerleave');
  const arcLengths=await page.locator('.donut-piece circle').evaluateAll(nodes=>nodes.map(n=>Number(n.getAttribute('stroke-dasharray').split(' ')[0])));
  assert.ok(Math.abs(arcLengths.reduce((a,b)=>a+b,0)-(314.159-6))<.01,'two devices retain visible gaps without changing Token totals');
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.summary.epoch.used=80;window.__CQG_TEST__.applySnapshot(data);});
  await page.waitForTimeout(450);
  const track=await page.locator('.quota-progress').boundingBox(),fill=await page.locator('.quota-progress i').boundingBox();
  assert.ok(Math.abs(fill.x+fill.width-track.x-track.width)<1,'remaining quota is anchored at the right edge');
  assert.ok(Math.abs(fill.width/track.width-.2)<.01,'20 percent remaining retains 20 percent width');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  const normalUsageColor=await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color);
  for(const [used,color] of [[91,'rgb(237, 141, 152)'],[90,'rgb(232, 191, 117)'],[80,normalUsageColor],[null,normalUsageColor]]){
    await page.evaluate(used=>{const data=structuredClone(window.__fixture);data.view.summary.epoch.used=used;window.__CQG_TEST__.applySnapshot(data);},used);
    assert.equal(await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color),color);
    assert.equal(await page.getByTestId('official-remaining').innerText(),used===null?'—':(100-used)+'%');
    assert.equal(await page.locator('.quota-progress').getAttribute('aria-valuenow'),used===null?null:String(100-used));
    if(used===91||used===90)assert.equal(await page.locator('.quota-progress i').evaluate(node=>getComputedStyle(node).backgroundColor),color);
  }
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.summary.epoch=null;window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('official-remaining').innerText(),'—');
  assert.equal(await page.getByTestId('official-remaining').evaluate(node=>getComputedStyle(node).color),normalUsageColor);
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.evaluate(()=>{
    window.__nativeDateNow=Date.now;window.__clockStart=Date.now();
    Date.now=()=>window.__clockStart;
    const data=structuredClone(window.__fixture);data.view.summary.epoch.reset_at=window.__clockStart/1000+7200;
    window.__countdownData=data;window.__CQG_TEST__.applySnapshot(data);
  });
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'2.0 小时');
  const dateBox=await page.getByTestId('refresh-date').boundingBox(),refreshBox=await page.locator('.refresh-card').boundingBox();
  assert.ok(dateBox.x-refreshBox.x>=13&&dateBox.x-refreshBox.x<=15&&refreshBox.y+refreshBox.height-dateBox.y-dateBox.height>=8,'refresh date sits at bottom left with padding');
  await page.evaluate(()=>{Date.now=()=>window.__clockStart+3600e3;window.__CQG_TEST__.applySnapshot(structuredClone(window.__countdownData));});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'1.0 小时');
  await page.evaluate(()=>{Date.now=()=>window.__clockStart+7200e3;window.__CQG_TEST__.applySnapshot(structuredClone(window.__countdownData));});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'等待刷新');
  await page.evaluate(()=>{const data=structuredClone(window.__countdownData);delete data.view.summary.epoch.reset_at;window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('refresh-remaining').innerText(),'—');
  await page.evaluate(()=>{Date.now=window.__nativeDateNow;window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));});
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','在线']);
  const usagePill=await page.locator('.device-state.using').boundingBox();

  assert.ok(usagePill.width<110&&usagePill.height===27,'the single-line activity badge stays compact and centered');
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);data.view.peers={};
    data.view.summary.devices.find(d=>d.id==='fixture-local').online=false;
    data.view.summary.devices.find(d=>d.id==='fixture-peer').online=true;
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','离线'],'connection badges do not use monitoring heartbeats');
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);
    data.view.summary.devices.find(d=>d.id==='fixture-peer').online=false;
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.deepEqual(await page.getByTestId('connection-state').allTextContents(),['在线','在线'],'connected peer stays online when its monitoring heartbeat is stale');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  const badges=await page.getByTestId('connection-state').evaluateAll(nodes=>nodes.map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,font:getComputedStyle(n).fontSize})));
  assert.deepEqual(badges,[{width:46,height:24,font:'11px'},{width:46,height:24,font:'11px'}]);
  assert.equal(await page.getByTestId('connection-state').first().evaluate(n=>getComputedStyle(n).color),'rgb(129, 206, 161)');
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.peers={};window.__CQG_TEST__.applySnapshot(data);});
  assert.equal(await page.getByTestId('connection-state').last().evaluate(n=>getComputedStyle(n).color),'rgb(237, 141, 152)');
  await page.screenshot({path:path.join(artifacts,'offline-badge.png')});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();
  await page.getByRole('option',{name:'每小时',exact:true}).click();
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.chart-bar').count(),30,'hour view contains thirty fixed two-minute buckets');
  assert.ok((await page.locator('.trend-card h2').innerText()).includes('每小时'));
  assert.equal((await page.locator('.charts-grid').boundingBox()).height,200);
  await page.screenshot({path:path.join(artifacts,'hour-preview.png')});
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.step,120);
  await page.getByRole('button',{name:'曲线',exact:true}).click();await page.waitForTimeout(700);
  const minuteCurve=(await page.evaluate(()=>window.__CQG_TEST__.getState())).trend;
  assert.equal(minuteCurve.step,60);
  assert.equal(minuteCurve.points.length,60);
  const beforePan=minuteCurve.start,panBox=await page.getByTestId('trend-hit').boundingBox();
  await page.evaluate(()=>window.__historyDelay=350);
  const offsetBefore=await page.locator('.trend-pan-content').getAttribute('transform');
  await page.mouse.move(panBox.x+panBox.width*.25,panBox.y+30);await page.mouse.down();
  await page.mouse.move(panBox.x+panBox.width*.75,panBox.y+30,{steps:10});await page.mouse.up();
  assert.equal(await page.locator('.trend-pan-content').getAttribute('transform'),offsetBefore,'dragging the plot never changes the time window');
  const slider=page.getByRole('slider',{name:'最近24小时时间滑块'});
  assert.equal(await slider.evaluate(n=>Number(n.max)-Number(n.min)),24*3600,'left slider end selects the hour ending 24 hours ago');
  const sliderBounds=await page.locator('.hour-slider').boundingBox(),hourLegendBounds=await page.locator('.trend-legend').boundingBox();
  assert.ok(sliderBounds.width<=185&&sliderBounds.height<=14&&sliderBounds.x+sliderBounds.width<=hourLegendBounds.x,'compact slider shares the bottom row without covering the legend');
  const slideFrames=await slider.evaluate(async n=>{
    n.value=Number(n.max)-1800;n.dispatchEvent(new Event('input',{bubbles:true}));
    const frames=[],start=performance.now();await new Promise(resolve=>{function tick(at){frames.push({at,end:window.__CQG_TEST__.getState().chartEnd});if(at-start<300)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});return frames;
  });
  assert.ok(new Set(slideFrames.map(f=>f.end).filter(end=>end!==null)).size>=8,'curve traverses intermediate time positions instead of jumping to the target');
  assert.ok(slideFrames.some(f=>f.end!==null&&!Number.isInteger(f.end)),'minute records scroll at fractional positions between bucket boundaries');
  await page.waitForTimeout(800);
  assert.equal(await page.evaluate(()=>window.__historyPeak),1,'history requests are coalesced and never overlap');
  await page.evaluate(()=>window.__historyDelay=0);
  assert.ok((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start<beforePan);
  assert.equal(await page.getByRole('button',{name:'回到实时',exact:true}).count(),1);
  const loadedCalls=await page.evaluate(()=>window.__commands.filter(c=>c.action==='chart_history').length);
  await slider.evaluate(n=>{n.value=Number(n.value)-180;n.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(200);
  assert.equal(await page.evaluate(()=>window.__commands.filter(c=>c.action==='chart_history').length),loadedCalls,'nearby slider changes reuse buffered history without bridge requests');
  await slider.evaluate(n=>{n.value=n.min;n.dispatchEvent(new Event('input',{bubbles:true}));});await page.waitForTimeout(400);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start,beforePan-86400);
  await page.getByRole('button',{name:'回到实时',exact:true}).click();
  assert.ok(await page.locator('.curve-reveal').evaluate(n=>n.getAnimations().some(a=>a.playState==='running')),'return to live redraws the curve from its beginning');
  await page.waitForTimeout(350);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).trend.start,beforePan);
  const axis=page.locator('.trend-svg .axis-text').first(),originalAxis=await axis.textContent();
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);for(const r of data.view.analytics.windows.hour_curve.rows)r.tokens*=10;window.__CQG_TEST__.applySnapshot(data);});
  await page.waitForTimeout(100);const changingAxis=await axis.textContent();
  await page.waitForTimeout(300);const expandedAxis=await axis.textContent();
  assert.notEqual(expandedAxis,originalAxis);assert.notEqual(changingAxis,expandedAxis,'larger values resize the axis gradually');
  const panScaleFrames=await slider.evaluate(async n=>{
    n.value=Number(n.max)-7200;n.dispatchEvent(new Event('input',{bubbles:true}));
    const frames=[],started=performance.now();await new Promise(resolve=>{function tick(at){frames.push(document.querySelector('.trend-svg .axis-text').textContent);if(at-started<650)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});return frames;
  });
  assert.equal(await axis.textContent(),originalAxis,'sliding to lower historical usage excludes the high live peak from the visible scale');
  assert.ok(new Set(panScaleFrames).size>3,'historical scale changes pass through intermediate values while sliding');
  await page.locator('.curve-reveal').evaluate(n=>n.dataset.liveEdgeIdentity='same-curve');
  await slider.evaluate(n=>{n.value=n.max;n.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.waitForTimeout(650);
  assert.equal(await page.locator('.curve-reveal').getAttribute('data-live-edge-identity'),'same-curve','sliding to live keeps the existing curve instead of replaying its entrance');
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).chartEnd,null,'the slider endpoint resumes live updates');
  assert.equal(await axis.textContent(),expandedAxis,'sliding back to higher live usage expands the scale again');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.waitForTimeout(100);const shrinkingAxis=await axis.textContent();
  await page.waitForTimeout(300);
  assert.equal(await axis.textContent(),originalAxis,'lower visible values shrink the hourly scale back to the current window');
  assert.notEqual(shrinkingAxis,expandedAxis,'the axis starts shrinking before the transition finishes');
  assert.notEqual(shrinkingAxis,originalAxis,'the axis shrinks gradually instead of jumping');
  assert.equal(await page.locator('.trend-svg').evaluate(n=>getComputedStyle(n).overflow),'hidden');
  for(let i=0;i<5;i++){await page.getByRole('button',{name:'柱状',exact:true}).click();await page.getByRole('button',{name:'曲线',exact:true}).click();}
  assert.equal(await page.locator('.chart-hover').count(),0,'rapid switches clear stale hover geometry');
  await page.screenshot({path:path.join(artifacts,'hour-minute-curve.png')});
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(450);
  assert.equal(await page.locator('.chart-bar').count(),30);

  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();
  await page.getByRole('option',{name:'每周',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.chart-bar').count(),7);
  assert.equal(await page.locator('.day-label').count(),7);
  const dayBox=await page.locator('.day-label').first().boundingBox(),legendBox=await page.locator('.trend-legend').boundingBox();
  assert.ok(dayBox.y+dayBox.height<legendBox.y,'legend sits below date labels');
  await page.screenshot({path:path.join(artifacts,'week-seven-days.png')});
  await page.getByRole('button',{name:'趋势时间范围',exact:true}).click();
  await page.getByRole('option',{name:'每天',exact:true}).click();
  await page.getByRole('button',{name:'曲线',exact:true}).click();await page.waitForTimeout(400);
  await page.screenshot({path:path.join(artifacts,'overview.png')});
  const mutations=await page.evaluate(async()=>{
    let count=0;const observer=new MutationObserver(list=>count+=list.length);
    document.querySelectorAll('.trend-svg,.donut-svg').forEach(node=>observer.observe(node,{subtree:true,attributes:true,childList:true}));
    for(let i=0;i<20;i++)window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture));
    await new Promise(r=>setTimeout(r,400));observer.disconnect();return count;
  });
  assert.equal(mutations,0,'identical polling performs zero SVG mutation or animation');
  await page.getByTestId('device-row').first().click();
  assert.equal(await page.locator('.user-summary-modal').count(),1);
  assert.equal(await page.locator('.user-token-grid>div').count(),6);
  assert.equal(await page.locator('.user-model-card').count(),6);
  assert.equal(await page.locator('.model-usage-track').first().evaluate(n=>getComputedStyle(n).height),'8px');
  assert.equal(await page.locator('.user-model-numbers').first().evaluate(n=>getComputedStyle(n).fontSize),'11px');
  assert.equal(await page.locator('.user-model-numbers').first().evaluate(n=>getComputedStyle(n).lineHeight),'16px');
  assert.ok(Math.abs((await page.locator('.model-usage-share b').allTextContents()).reduce((sum,value)=>sum+parseFloat(value),0)-100)<.11);
  assert.equal(await page.locator('.palette button').count(),0,'settings stay behind the user settings button');
  await page.screenshot({path:path.join(artifacts,'user-cycle-summary.png')});
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture),rows=data.view.analytics.windows.cycle.rows,source=rows.find(row=>row.device===data.settings.device_id);
    for(const row of rows)if(row.device===source.device)row.model=row.model==='gpt-5.5'?'gpt-6-astra':'gpt-5.6-sol';
    window.__CQG_TEST__.applySnapshot(data);
  });
  assert.equal(await page.locator('.user-model-card').count(),4);
  const luna=page.locator('.user-model-card').filter({hasText:'gpt-5.6-luna'});
  assert.equal(await luna.locator('.user-model-token').innerText(),'0 Token');
  assert.equal(await luna.locator('.model-usage-share b').innerText(),'0.0%');
  assert.ok(!(await luna.innerText()).includes('本周期未使用'));
  const modelLayout=await page.locator('.user-summary-modal').evaluate(n=>({primary:n.querySelector('.user-cycle-primary').getBoundingClientRect().bottom,details:n.querySelector('.user-token-grid').getBoundingClientRect().top,cards:[...n.querySelectorAll('.user-model-card')].map(c=>{const r=c.getBoundingClientRect();return {x:r.x,y:r.y,bottom:r.bottom,width:r.width,overflow:c.scrollWidth>c.clientWidth};})}));
  assert.ok(modelLayout.cards.every(c=>c.y===modelLayout.cards[0].y&&c.y>modelLayout.primary&&c.bottom<modelLayout.details&&c.width<150&&!c.overflow),'four compact model cards occupy one row immediately below total usage');
  await page.waitForTimeout(300);
  await page.screenshot({path:path.join(artifacts,'user-four-model-cards.png')});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.getByRole('button',{name:'用户设置',exact:true}).click();
  assert.equal(await page.getByRole('heading',{name:'用户设置',exact:true}).count(),1);
  assert.equal(await page.locator('.palette button').count(),8);
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.waitForTimeout(200);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).selectedDevice,'','closing user settings clears selection');
  assert.equal(await page.locator('.device-heading').count(),0);
  await page.getByRole('button',{name:'筛选模型',exact:true}).click();
  assert.deepEqual(await page.locator('.select-option>span:first-child').allTextContents(),['全部模型','gpt-5.10','gpt-5.9','gpt-5.5','gpt-5.3-codex']);
  await page.locator('.select-menu').evaluate(e=>e.dataset.identity='persistent-menu');
  for(let i=0;i<20;i++)await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.locator('.select-menu').getAttribute('data-identity'),'persistent-menu');
  assert.equal(await page.getByTestId('device-row').first().evaluate(e=>e.classList.contains('selected')),false);
  await page.screenshot({path:path.join(artifacts,'dropdown.png')});
  await page.getByRole('option',{name:'gpt-5.5',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().model),'gpt-5.5');
  await page.getByRole('button',{name:'筛选用户',exact:true}).click();
  await page.getByRole('option',{name:'全部用户',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.trend-line').count(),2,'all users have separate colored lines');
  assert.deepEqual(await page.locator('.trend-legend-share').allTextContents(),[(initial.view.analytics.windows.day.rows.filter(r=>r.device==='fixture-local'&&r.model==='gpt-5.5').reduce((sum,r)=>sum+r.tokens,0)/450e6*100).toFixed(1)+'%',(initial.view.analytics.windows.day.rows.filter(r=>r.device==='fixture-peer'&&r.model==='gpt-5.5').reduce((sum,r)=>sum+r.tokens,0)/450e6*100).toFixed(1)+'%']);
  assert.equal(new Set(await page.locator('.trend-line').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('stroke')))).size,2);
  for(let i=0;i<3;i++)await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().user),'','explicit all users selection survives refresh');
  await page.screenshot({path:path.join(artifacts,'all-users-lines.png')});
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.chart-bar').count(),48,'24 time buckets contain two stacked device segments');
  assert.equal(new Set(await page.locator('.chart-bar').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('fill')))).size,2);
  assert.equal(await page.locator('clipPath[id^="bar-round-"] rect').count(),24);
  assert.equal(await page.locator('#bar-round-3 rect').getAttribute('rx'),'3');
  assert.equal(await page.locator('.chart-bar').nth(27).getAttribute('clip-path'),'url(#bar-round-3)');
  await page.screenshot({path:path.join(artifacts,'all-users-stacked.png')});
  await page.getByRole('button',{name:'曲线',exact:true}).click();
  await page.waitForTimeout(90);
  const reveal=await page.locator('.curve-reveal').evaluate(n=>({name:getComputedStyle(n).animationName,scale:new DOMMatrix(getComputedStyle(n).transform).a}));
  assert.equal(reveal.name,'curve-draw');assert.ok(reveal.scale>0&&reveal.scale<1,'curve is being drawn from left to right');
  await page.waitForTimeout(650);
  assert.equal(await page.locator('.curve-reveal').evaluate(n=>new DOMMatrix(getComputedStyle(n).transform).a),1);
  const runningAnimation=await page.locator('.curve-reveal').evaluate(n=>n.getAnimations()[0]?.currentTime);
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.ok(await page.locator('.curve-reveal').evaluate(n=>n.getAnimations()[0]?.currentTime)>=runningAnimation,'snapshot does not replay the entrance');
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(60);
  assert.equal(await page.locator('.bar-chart').evaluate(n=>getComputedStyle(n).animationName),'bars-rise');
  assert.ok(await page.locator('.bar-chart').evaluate(n=>new DOMMatrix(getComputedStyle(n).transform).d)<1,'bars rise from the baseline');
  await page.waitForTimeout(420);

  await page.getByRole('button',{name:'筛选用户',exact:true}).click();
  await page.getByRole('option',{name:/^橙猫猫 · 本机/}).click();
  assert.equal(await page.evaluate(()=>window.__CQG_TEST__.getState().user),'fixture-local');
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(350);
  assert.equal(await page.locator('.chart-bar').count(),24);
  await page.screenshot({path:path.join(artifacts,'bars.png')});
  await page.getByTestId('device-row').first().click();
  await page.getByRole('button',{name:'用户设置',exact:true}).click();
  assert.equal(await page.locator('.palette button').count(),8);
  await page.locator('.user-note-label input').fill('测试工作站');
  await page.locator('.palette button').nth(4).click();
  await page.getByRole('button',{name:'保存用户设置',exact:true}).click();
  await page.locator('.modal-backdrop').waitFor({state:'hidden'});
  assert.equal(await page.locator('.device-row.selected').count(),0,'saving user settings clears the device highlight');
  assert.equal(await page.evaluate(()=>window.__commands.at(-1).action),'color_save');
  assert.ok((await page.getByTestId('device-row').first().innerText()).includes('测试工作站'));
  assert.equal(await page.locator('.trend-legend-share').first().evaluate(n=>getComputedStyle(n).color),'rgb(237, 130, 153)');
  const firstRow=await page.getByTestId('device-row').first().boundingBox(),secondRow=await page.getByTestId('device-row').last().boundingBox();
  await page.mouse.move(firstRow.x+80,firstRow.y+25);await page.mouse.down();
  await page.mouse.move(secondRow.x+80,secondRow.y+30,{steps:10});await page.mouse.up();await page.waitForTimeout(220);
  assert.equal(await page.locator('.modal-backdrop').count(),0,'dragging does not open user settings');
  assert.deepEqual(await page.getByTestId('device-row').evaluateAll(rows=>rows.map(row=>row.dataset.deviceId)),['fixture-peer','fixture-local']);
  assert.equal(await page.locator('.legend-name').first().innerText(),'DESKTOP-N41609F');
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await page.getByTestId('device-row').first().getAttribute('data-device-id'),'fixture-peer');
  for(const target of ['stats','accounts','sync','settings','help','overview']){await page.getByTestId('nav-'+target).click();await page.waitForTimeout(340);await page.screenshot({path:path.join(artifacts,target+'.png')});}
  await page.getByTestId('nav-sync').click();await page.waitForTimeout(330);
  await page.getByRole('button',{name:'高级连接设置',exact:true}).click();
  const relay=page.getByRole('checkbox',{name:'仅使用加密中转',exact:true});
  assert.equal(await relay.isChecked(),true,'existing relay preference initializes the connection form');
  await relay.uncheck();
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  assert.equal(await relay.isChecked(),false,'polling preserves an edited connection preference');
  await page.getByRole('button',{name:'保存连接设置',exact:true}).click();
  const connection=await page.evaluate(()=>window.__commands.filter(c=>c.action==='connection_save').at(-1));
  assert.deepEqual(connection.payload,{force_relay:false});
  await page.getByTestId('nav-settings').click();await page.waitForTimeout(330);
  await page.getByTestId('settings-user').last().click();
  assert.equal(await page.locator('.modal h2').innerText(),'用户设置');
  assert.equal(await page.locator('.user-note-label input').inputValue(),'测试工作站');
  await page.getByRole('button',{name:'关闭对话框',exact:true}).click();
  await page.waitForTimeout(200);
  assert.equal((await page.evaluate(()=>window.__CQG_TEST__.getState())).selectedDevice,'','closing user settings clears selection');
  await page.getByRole('button',{name:'添加 EXE',exact:true}).click();
  assert.ok((await page.locator('.program-list').innerText()).includes('extra-codex.exe'));
  await page.getByRole('button',{name:'保存监测设置',exact:true}).click();
  const saved=await page.evaluate(()=>window.__commands.filter(c=>c.action==='settings_save').at(-1));
  assert.deepEqual(Object.keys(saved.payload.settings).sort(),['autostart','codex_home','interval','multiplier','name','program_paths','quota']);
  await page.getByRole('switch',{name:'Codex 自动限额'}).click();
  await page.getByRole('button',{name:'确认',exact:true}).click();
  const limit=await page.evaluate(()=>window.__commands.filter(c=>c.action==='limit_toggle').at(-1));
  assert.equal(limit.payload.account,'fixture-account');assert.equal(limit.payload.confirmed,true);
  await page.getByTestId('nav-overview').click();await page.waitForTimeout(330);
  await page.getByRole('button',{name:'曲线',exact:true}).click();
  await page.evaluate(()=>{
    const data=structuredClone(window.__fixture);
    for(const row of data.view.analytics.windows.day.rows)if(row.device==='fixture-local'&&row.model==='gpt-5.5')row.tokens=row.bucket===12?9e6:1000;
    for(const w of Object.values(data.view.analytics.windows))w.quota_rows=w.rows.map(r=>({device:r.device,model:r.model,bucket:r.bucket,quota:r.tokens/450e6*100}));
    window.__fixture=data;window.__CQG_TEST__.applySnapshot(data);
  });await page.waitForTimeout(400);
  async function hoverAt(fraction){await page.evaluate(fraction=>{const hit=document.querySelector('[data-testid="trend-hit"]'),r=hit.getBoundingClientRect();hit.dispatchEvent(new PointerEvent('pointermove',{clientX:r.left+r.width*fraction,clientY:r.top+30,bubbles:true}));},fraction);await page.waitForTimeout(170);return page.locator('.chart-tooltip').boundingBox();}
  const lowA=await hoverAt(.08),lowB=await hoverAt(.18),peakTip=await hoverAt(12/23);
  await page.screenshot({path:path.join(artifacts,'tooltip-layout-review.png')});
  assert.ok(Math.abs(lowA.y-lowB.y)<.5,'tooltip keeps a fixed baseline away from the curve');
  assert.ok(peakTip.y<=lowA.y+.5,'expanded cache tooltip stays above a high peak');
  const hitBox=await page.getByTestId('trend-hit').boundingBox();
  assert.ok(peakTip.y+peakTip.height<hitBox.y+hitBox.height*.1-5,'tooltip clears the actual peak');
  await page.screenshot({path:path.join(artifacts,'tooltip-peak-avoidance.png')});
  assert.equal(await page.locator('.tooltip-total-percent').innerText(),'2.00%');
  await page.getByRole('button',{name:'筛选用户',exact:true}).click();
  await page.getByRole('option',{name:'全部用户',exact:true}).click();
  for(const kind of ['曲线','柱状']){
    await page.getByRole('button',{name:kind,exact:true}).click();await page.waitForTimeout(450);
    await hoverAt(0);
    const expected=await page.evaluate(()=>{
      const rows=window.__fixture.view.analytics.windows.day.rows.filter(r=>r.bucket===0&&r.model==='gpt-5.5'&&['fixture-local','fixture-peer'].includes(r.device));
      return {total:(rows.reduce((sum,r)=>sum+r.tokens,0)/450e6*100).toFixed(2)+'%',users:Object.fromEntries(rows.map(r=>[r.device,(r.tokens/450e6*100).toFixed(2)+'%']))};
    });
    assert.equal(await page.locator('.tooltip-total-percent').innerText(),expected.total);
    for(const [id,value] of Object.entries(expected.users))assert.equal(await page.locator('.tooltip-series-row[data-device="'+id+'"] .tooltip-user-quota').innerText(),value);
    assert.ok(await page.locator('.chart-tooltip').evaluate(n=>n.scrollWidth<=n.clientWidth),'tooltip content fits');
    for(const column of ['.tooltip-series-value','.tooltip-user-percent']){
      const rightEdges=await page.locator(column).evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().right));
      assert.ok(Math.abs(rightEdges[0]-rightEdges[1])<.5,'tooltip numeric columns align');
    }

  }
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.settings.device_notes[data.view.identity.account]={'fixture-local':'橙猫猫','fixture-peer':'A'};window.__CQG_TEST__.applySnapshot(data);});
  await hoverAt(0);
  const gap=await page.locator('.tooltip-series-row').first().evaluate(row=>row.querySelector('.tooltip-series-value').getBoundingClientRect().left-row.querySelector('.tooltip-series-name').getBoundingClientRect().right);
  assert.ok(gap<=8.5,'short names do not stretch away from tokens');
  await page.screenshot({path:path.join(artifacts,'tooltip-quota-percent.png')});
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);data.view.analytics.windows.day.quota_pending_rows=[{device:'fixture-local',model:'gpt-5.5',bucket:0}];window.__CQG_TEST__.applySnapshot(data);});
  await hoverAt(0);
  assert.equal(await page.locator('.tooltip-total-percent').innerText(),'0.24%');
  assert.notEqual(await page.locator('.tooltip-series-row[data-device="fixture-local"] .tooltip-user-quota').innerText(),'待更新');
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);for(const key of ['day','cycle'])data.view.analytics.windows[key].quota_estimate_rows=[{device:'fixture-local',model:'gpt-5.5',bucket:0,quota:.12}];window.__CQG_TEST__.applySnapshot(data);});
  await hoverAt(0);
  assert.equal(await page.locator('.tooltip-total-percent').innerText(),'0.24%');
  assert.ok(!(await page.locator('.donut-share').allInnerTexts()).some(text=>text.startsWith('≈ ')));
  assert.equal(await page.locator('.quota-estimate-note').count(),0);
  await page.screenshot({path:'test-artifacts/official-quota-calibration.png'});
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await hoverAt(0);
  assert.notEqual(await page.locator('.tooltip-total-percent').innerText(),'待更新');
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);for(const w of Object.values(data.view.analytics.windows)){for(const r of w.rows){r.cache_tokens=Math.floor(r.tokens*.8);r.detail_missing=0;}for(const r of w.quota_rows)r.cache_quota=r.quota*.1;}window.__CQG_TEST__.applySnapshot(data);});
  await page.getByRole('button',{name:'曲线内容模式',exact:true}).click();
  await page.getByRole('option',{name:'曲线＋缓存模式',exact:true}).click();await page.waitForTimeout(450);
  assert.equal(await page.locator('.trend-cache-line').count(),2);
  assert.equal(await page.locator('.trend-line').count(),2);
  assert.ok(await page.locator('.chart-controls').evaluate(n=>n.scrollWidth<=n.clientWidth));
  await hoverAt(0);await page.screenshot({path:path.join(artifacts,'cache-combined.png')});
  await page.getByRole('button',{name:'柱状',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.trend-cache-line').count(),0,'combined mode bars never overlay a cache curve');
  assert.ok(await page.locator('.chart-bar').count()>0);
  await page.getByRole('button',{name:'曲线',exact:true}).click();await page.waitForTimeout(400);
  assert.equal(await page.locator('.trend-cache-line').count(),2,'switching back to curves restores the cache overlay');
  await page.getByRole('button',{name:'曲线内容模式',exact:true}).click();
  await page.getByRole('option',{name:'缓存模式',exact:true}).click();await page.waitForTimeout(450);
  assert.equal(await page.locator('.trend-cache-line').count(),0);
  assert.equal(await page.locator('.trend-line').count(),2);
  assert.deepEqual(await page.locator('.trend-line').evaluateAll(nodes=>nodes.map(n=>getComputedStyle(n).strokeDasharray)),['5px, 4px','5px, 4px']);
  await hoverAt(0);await page.screenshot({path:path.join(artifacts,'cache-only.png')});
  await page.getByRole('button',{name:'曲线内容模式',exact:true}).click();
  await page.getByRole('option',{name:'曲线模式',exact:true}).click();
  await page.evaluate(()=>{const data=structuredClone(window.__fixture);for(const w of Object.values(data.view.analytics.windows))w.quota_ready=false;window.__CQG_TEST__.applySnapshot(data);});
  await hoverAt(0);
  assert.equal(await page.locator('.tooltip-total-percent').innerText(),'—');
  assert.deepEqual(await page.locator('.tooltip-user-quota').allTextContents(),['—','—']);
  await page.evaluate(()=>window.__CQG_TEST__.applySnapshot(structuredClone(window.__fixture)));
  await page.getByRole('button',{name:'曲线',exact:true}).click();await hoverAt(.5);
  assert.deepEqual(errors,[]);
  const measure=await page.evaluate(async()=>{
    const frames=[];let previous=performance.now(),at=previous;
    await new Promise(resolve=>{function tick(now){frames.push(now-previous);previous=now;if(now-at<1000){const target=document.querySelector('[data-testid="trend-hit"]'),bounds=target.getBoundingClientRect();target.dispatchEvent(new PointerEvent('pointermove',{clientX:bounds.x+bounds.width*(.5+Math.sin(now/180)*.4),clientY:bounds.y+40,bubbles:true}));requestAnimationFrame(tick);}else resolve();}requestAnimationFrame(tick);});
    frames.sort((a,b)=>a-b);return {frames:frames.length,median:frames[Math.floor(frames.length*.5)],p95:frames[Math.floor(frames.length*.95)]};
  });
  assert.equal(await page.locator('.chart-hover').count(),1);
  await page.reload();
  await page.locator('.app-shell.ready').waitFor();await page.waitForTimeout(600);
  assert.equal(await page.locator('.toast').count(),0);
  assert.equal(await page.getByRole('button',{name:'筛选模型',exact:true}).innerText(),'全部模型');
  await page.screenshot({path:path.join(artifacts,'overview.png')});
  assert.equal(await page.getByRole('button',{name:'界面主题',exact:true}).innerText(),'');
  assert.equal(await page.locator('.theme-icon').count(),1);
  async function chooseTheme(label){await page.getByRole('button',{name:'界面主题',exact:true}).click();await page.getByRole('option',{name:label,exact:true}).click();await page.waitForTimeout(250);}
  await chooseTheme('白天模式');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  assert.equal(await page.locator('.app-shell').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(243, 245, 248)');
  assert.ok(await page.locator('.titlebar').evaluate(n=>n.scrollWidth<=n.clientWidth));
  await page.screenshot({path:path.join(artifacts,'theme-light.png')});
  await page.getByTestId('device-row').first().click();await page.waitForTimeout(200);
  await page.screenshot({path:path.join(artifacts,'theme-light-modal.png')});
  await page.keyboard.press('Escape');
  await page.emulateMedia({colorScheme:'dark'});
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await chooseTheme('跟随系统');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.emulateMedia({colorScheme:'light'});await page.waitForTimeout(100);
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await chooseTheme('黑夜模式');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:path.join(artifacts,'theme-dark.png')});
  assert.deepEqual(errors,[]);
  await writeFile(path.join(artifacts,'result.json'),JSON.stringify({ok:true,errors,headlessFrameSample:measure},null,2));
  console.log('OFFLINE_VUE_UI_DATA_LAYOUT_SELECTION_MENU_ALL_PAGES_OK',JSON.stringify(measure));
}finally{await browser.close();await new Promise(r=>server.close(r));}
